apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nkrvkwa8e-nodejs
  janus-idp.io/tekton: nkrvkwa8e-nodejs
  backstage.io/kubernetes-id: nkrvkwa8e-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nkrvkwa8e-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
